from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('engineers/', views.engineers_view, name='engineers'),
    path('engineers/<int:user_id>/view/', views.view_as_user, name='view_as_user'),
    path('engineers/stop/', views.stop_view_as, name='stop_view_as'),
    path('van-kit/', views.van_kit, name='van_kit'),
    path('van-kit/add/', views.van_kit_add, name='van_kit_add'),
    path('van-kit/bulk/', views.van_kit_bulk_add, name='van_kit_bulk_add'),
    path('van-kit/scan/', views.van_kit_scan, name='van_kit_scan'),
    path('van-kit/<int:pk>/toggle/', views.van_kit_toggle, name='van_kit_toggle'),
    path('van-kit/<int:pk>/delete/', views.van_kit_delete, name='van_kit_delete'),
    path('van-kit/reset-ordered/', views.van_kit_reset_ordered, name='van_kit_reset_ordered'),
    path('', views.dashboard, name='dashboard'),
    path('jobs/', views.jobs_all, name='jobs_all'),
    path('jobs/<int:pk>/admin-edit/', views.job_admin_edit, name='job_admin_edit'),
    path('jobs/add/', views.add_job, name='add_job'),
    path('jobs/bulk/preview/', views.bulk_add_preview, name='bulk_add_preview'),
    path('jobs/bulk/confirm/', views.bulk_add_confirm, name='bulk_add_confirm'),
    path('bulk-pastes/', views.bulk_pastes, name='bulk_pastes'),
    path('bulk-pastes/<int:pk>/', views.bulk_paste_detail, name='bulk_paste_detail'),
    path('audit-logs/', views.audit_logs, name='audit_logs'),
    path('jobs/<int:pk>/delete/', views.delete_job, name='delete_job'),
    path('jobs/<int:pk>/appointment/', views.update_appointment, name='update_appointment'),
    path('jobs/<int:pk>/notes/', views.update_notes, name='update_notes'),
    path('jobs/<int:pk>/mark/', views.mark_job, name='mark_job'),
    path('jobs/reorder/', views.reorder_jobs, name='reorder_jobs'),
    path('places/autocomplete/', views.places_autocomplete, name='places_autocomplete'),
    path('places/details/', views.place_details, name='place_details'),
    path('unlock/', views.unlock_order, name='unlock_order'),
    path('plan/', views.plan_route, name='plan_route'),
    path('clear/', views.clear_route, name='clear_route'),
    path('settings/', views.settings_view, name='settings'),
    path('earnings/', views.earnings_view, name='earnings'),
]
