# Generated by Django 5.2.11 on 2026-08-11 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_label', models.CharField(blank=True, default='Home / Depot', help_text='Label for your start point', max_length=200)),
                ('start_location', models.CharField(blank=True, help_text='Postcode or address you start from', max_length=255)),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('start_lng', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Engineer settings',
                'verbose_name_plural': 'Engineer settings',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, help_text='Optional job / TT number', max_length=100)),
                ('location', models.CharField(help_text='Full address or just a postcode', max_length=255)),
                ('appointment_type', models.CharField(choices=[('AM', 'AM (8am – 1pm)'), ('PM', 'PM (1pm – 6pm)'), ('ALLDAY', 'All day')], default='ALLDAY', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('geocode_display', models.CharField(blank=True, max_length=255)),
                ('route_order', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_arrival', models.TimeField(blank=True, null=True)),
                ('leg_miles_from_previous', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['job_date', 'route_order', 'id'],
            },
        ),
    ]
