# Generated by Django 5.2.11 on 2026-08-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField(unique=True)),
                ('geometry', models.JSONField(default=list, help_text='List of [lat, lng] points along the driving route')),
                ('total_miles', models.FloatField(default=0)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, default='osrm', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-job_date'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='leg_minutes_from_previous',
            field=models.PositiveIntegerField(blank=True, help_text='Driving minutes from previous stop along roads', null=True),
        ),
    ]
