# Generated by Django 5.2.11 on 2026-08-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_dayroute_job_leg_minutes_from_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineersettings',
            name='start_display',
            field=models.CharField(blank=True, help_text='Resolved street / place for the start point', max_length=255),
        ),
    ]
