# Generated by Django 5.2.11 on 2026-08-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_engineersettings_start_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayroute',
            name='order_locked',
            field=models.BooleanField(default=False, help_text='When true, keep manual drag order instead of auto-optimising'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=10),
        ),
    ]
