# Generated by Django 5.2.11 on 2026-08-16 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_dayroute_order_locked_job_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dayroute',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engineersettings',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayroute',
            name='job_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='dayroute',
            constraint=models.UniqueConstraint(fields=('user', 'job_date'), name='planner_dayroute_user_job_date_uniq'),
        ),
    ]
