# Generated by Django 5.2.11 on 2026-08-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_user_owned_jobs_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VanKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_code', models.CharField(help_text='Code used when marking as ordered', max_length=64, unique=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('ordered', models.BooleanField(default=False, help_text='Green when this product has been ordered')),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
    ]
