# Generated by Django 5.2.11 on 2026-09-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_seed_van_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_type',
            field=models.CharField(blank=True, choices=[('managed_install', 'Managed install'), ('self_install', 'Self install'), ('sogea_repair', 'SOGEA repair'), ('ogea_repair', 'OGEA repair'), ('copper_repair', 'Copper repair')], default='', help_text='Parsed from task description on bulk import', max_length=20),
        ),
    ]
