# Generated by Django 5.2.11 on 2026-09-13 19:11

import planner.planner_day
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_job_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_date',
            field=models.DateField(default=planner.planner_day.planner_today, help_text='Planning day (rolls to tomorrow after 9pm local)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Complete'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10),
        ),
    ]
