# Generated by Django 5.2.11 on 2026-09-14 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_planner_day_and_failed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField(help_text='Planner day the paste was applied to')),
                ('raw_text', models.TextField()),
                ('search_text', models.TextField(blank=True, help_text='Lowercased refs, postcodes, addresses for search')),
                ('jobs_added', models.PositiveIntegerField(default=0)),
                ('jobs_removed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Account that submitted the paste', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_pastes_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Engineer whose route the paste was applied to', on_delete=django.db.models.deletion.CASCADE, related_name='bulk_pastes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
