# Generated by Django 5.2.11 on 2026-09-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_bulk_paste_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Complete'), ('mpu', 'MPU'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10),
        ),
    ]
